### ISSUE TITLE
feat: Add Friends screen

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#94]
### What feature?

- [ ] Add friends screen with the list of all friends
- [ ] Send request to add friend
- [ ] See friends that send a request to you
- [ ] Accept/deny requests

### Add screenshots

![Friends](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/60ced6c9-f2c8-475d-ab3c-fb99feb59128)

**Comment by maksym-hladii** [comment]
UPDATE

### What feature?

- [ ] Add friends screen with the list of all friends
- [ ] A possibility to follow / unfollow a user (after clicking the "Follow" button, its label changes to "Following")

### Add screenshots

![Friends](

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/e2cf3fd4-28c4-4bbb-9881-c308e7332cc6)

)

**Comment by maksym-hladii** [comment]
### UPDATE:

### What feature?

- [ ] Add friends screen with three tabs: "Find the friends", "Followers" and "Following"
- [ ] A possibility to follow / unfollow a user (after clicking the "Follow" button, its label changes to "Following")

### Add screenshots

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/3142aa73-8d1d-4dc4-9d62-4edda1245cde)

**Comment by maksym-hladii** [comment]
**FIX:**
- [ ] The white background beneath the "Followers" and "Following" labels

**Comment by maksym-hladii** [comment]
**Fix the issues, caused by the imperfect requirements, provided by the QA (me):**

- [ ] **"Find friends" tab:** Make the users, who have just been followed by the current user, to disappear after switching to another tab (to avoid the need to refresh the page)

- [ ] **"Following" tab:** Make the users, whom the current user has just unfollowed, to stay on the tab until switching to another tab (in case the current user made a mistake)
